#!/bin/env python3
# -*- coding: utf-8 -*-
import collections
import importlib
import json
import traceback

import discord

_PluginSpec = collections.namedtuple("PluginSpec", (
    "module",
    "disallowed_channels",
    "disallowed_servers",
    "allowed_channels", #exceptions to allow responses on otherwise disallowed servers
))
_PLUGINS = tuple(_PluginSpec(
    importlib.import_module('.' + plugin_spec['plugin'], 'lib8squall_plugins'),
    plugin_spec.get("disallowedChannels", ()),
    plugin_spec.get("disallowedServers", ()),
    plugin_spec.get("allowedChannels", ()),
) for plugin_spec in json.load(open('./plugin-specs.json')))

class Magic8Squall(discord.Client):
    async def on_ready(self):
        print('Logged on as {}'.format(self.user))

    async def on_message(self, message):
        #take a look at https://discordpy.readthedocs.io/en/latest/api.html#message
        #to see what data you can play with

        #no point in processing our own messages
        if message.author == self.user:
            return
            
        try:
            for plugin in _PLUGINS:
                if message.channel.id in plugin.disallowed_channels:
                    continue
                if message.channel.guild.id in plugin.disallowed_servers:
                    if message.channel.id not in plugin.allowed_channels:
                        continue
                        
                if await plugin.module.handle_message(self, message):
                    break #message was handled
            else:
                if client.user in message.mentions:
                    help_summaries = []
                    for plugin in _PLUGINS:
                        if message.channel.id in plugin.disallowed_channels:
                            continue
                        if message.channel.guild.id in plugin.disallowed_servers:
                            if message.channel.id not in plugin.allowed_channels:
                                continue
                                
                        help_summaries.append(plugin.module.HELP_SUMMARY.strip())
                        
                    if help_summaries:
                        await message.channel.send(
                            content="\n\n".join(help_summaries),
                            delete_after=(4.0 * len(help_summaries)),
                        )
        except Exception:
            traceback.print_exc()
            
client = Magic8Squall()
client.run(open('./discord-token').read().strip())
